export const GET_POST_FAILURE = 'GET_POST_FAILURE';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAILURE = 'GET_COMMENT_FAILURE';

export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const CLEAR_INPUT_VALUE = 'CLEAR_INPUT_VALUE';
export const SHOW_FILM = 'SHOW_FILM'
export const SEARCH = 'SEARCH';
